In [20]:
import pandas as pd

In [21]:
data = pd.read_pickle('../Data/preprocessed_data/preprocessed_data.pkl')
data.head()

Price,Close,High,Low,Open,Volume,sma-5,sma-20,sma-50,Close-sma-50,sma_5-sma_20,...,Rolling_minimum_20,Rolling_std,rolling_volatility,RVOL,Volume_MA_20,Volume_Change,wilder_atr,upper_barrier,lower_barrier,Label
49,41.122002,41.199501,40.724998,41.099998,59434000,40.651701,39.509850,38.62706,2.494942,1.141851,...,37.4935,1.201074,0.011484,0.868399,68440900.0,3484000.0,0.604991,42.331983,40.517011,-1.0
50,41.826000,41.870998,41.264500,41.289501,78452000,40.942101,39.699675,38.72120,3.104800,1.242426,...,37.4935,1.253656,0.011550,1.114662,70381900.0,19018000.0,0.615277,43.056554,41.210723,0.0
51,41.957500,42.192001,41.650002,41.776501,71726000,41.243201,39.869050,38.82134,3.136161,1.374151,...,37.4935,1.320073,0.011340,1.005559,71329500.0,-6726000.0,0.610043,43.177586,41.347458,0.0
52,41.788502,41.985001,41.472000,41.950001,59974000,41.517601,40.028150,38.93804,2.850462,1.489451,...,37.4935,1.351282,0.011471,0.844381,71027200.0,-11752000.0,0.603111,42.994724,41.185390,0.0
53,41.519001,41.674999,40.819000,41.650002,74946000,41.642601,40.191225,39.02518,2.493821,1.451376,...,37.4935,1.322853,0.011330,1.046495,71616200.0,14972000.0,0.629282,42.777565,40.889719,0.0

In [22]:
data.head()

Price,Close,High,Low,Open,Volume,sma-5,sma-20,sma-50,Close-sma-50,sma_5-sma_20,...,Rolling_minimum_20,Rolling_std,rolling_volatility,RVOL,Volume_MA_20,Volume_Change,wilder_atr,upper_barrier,lower_barrier,Label
49,41.122002,41.199501,40.724998,41.099998,59434000,40.651701,39.509850,38.62706,2.494942,1.141851,...,37.4935,1.201074,0.011484,0.868399,68440900.0,3484000.0,0.604991,42.331983,40.517011,-1.0
50,41.826000,41.870998,41.264500,41.289501,78452000,40.942101,39.699675,38.72120,3.104800,1.242426,...,37.4935,1.253656,0.011550,1.114662,70381900.0,19018000.0,0.615277,43.056554,41.210723,0.0
51,41.957500,42.192001,41.650002,41.776501,71726000,41.243201,39.869050,38.82134,3.136161,1.374151,...,37.4935,1.320073,0.011340,1.005559,71329500.0,-6726000.0,0.610043,43.177586,41.347458,0.0
52,41.788502,41.985001,41.472000,41.950001,59974000,41.517601,40.028150,38.93804,2.850462,1.489451,...,37.4935,1.351282,0.011471,0.844381,71027200.0,-11752000.0,0.603111,42.994724,41.185390,0.0
53,41.519001,41.674999,40.819000,41.650002,74946000,41.642601,40.191225,39.02518,2.493821,1.451376,...,37.4935,1.322853,0.011330,1.046495,71616200.0,14972000.0,0.629282,42.777565,40.889719,0.0

In [23]:
x = data.drop(columns=['Label'])
y = data['Label']

In [24]:
split_index = int(len(data)*0.8)
x_train= x[:split_index]
y_train=y[:split_index]

x_test=x[split_index:]
y_test = y[split_index:]

In [25]:
print(len(x_train),len(y_train))

1897 1897

In [26]:
print(len(x_test),len(y_test))

475 475

In [27]:
x_train.to_pickle('../Data/train_test_data/x_train.pkl')
y_train.to_pickle('../Data/train_test_data/y_train.pkl')
x_test.to_pickle('../Data/train_test_data/x_test.pkl')
y_test.to_pickle('../Data/train_test_data/y_test.pkl')